pipeline {
    agent any

    environment {
        cluster = "fidevappprod"
        service = "fidevappsvc"
    }

    stages {
        stage('Deploy to ECS Prod') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-west-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
    post {
        always {
            echo 'Slack Notifications'
            slackSend channel: '#projectfidevapp',
            color: COLOR_MAP[currentBuild.currentResult],
            message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More infor at: ${env.BUILD_URL}"
        }
    }
}